### ISSUE TITLE
Please help update this library for the new version of slate.js.

### ISSUE THREAD

**Issue by axtew** [enzoferey/slate-instant-replace#2]
Please help update this library for the new version of slate.js. For example, extends () was removed in version 0.37.

**Comment by enzoferey** [comment]
Hi @axtew ! Thanks for opening the issue 😄 I see @FWirtz like on your issue and I have discussed it with him on the past on Twitter, let me explain you.

I'm totally okay upgrading the library, I have seen there were major changes in the last months and the new API seems way cleaner, so the library code itself should be way easier to write and read. My point for not doing so two-three months ago was that I was expecting the SlateJS team to change quite a lot of things (as it has been the case), so I didn't want to move to some unstable/"will change soon" new API. I preferred waiting a little bit for a more stable thing so I don't need to work twice. Also, the APIs were just deprecated, so it didn't block anybody to still use the last version of Slate.

I have just checked now and the `change.extends()` is indeed removed, so now it's a more important topic. I will find out the new way of achieving what the libraries does and eventually publish in the next days a support for the latest version (which is `0.44.6` at the moment).

**Comment by enzoferey** [comment]
Update for you guys, I have just pushed a working version in `0.44.6` and tests passing but I split up functions in different files and I have just a plain Babel configuration so I can't bundle the files together. 

I still need to update docs a little bit and update the examples and it's pretty late here already so I will review once again everything tomorrow and move to a Webpack build system. Expect a package version tomorrow ! 😉

**Comment by enzoferey** [comment]
Published ! 

[https://www.npmjs.com/package/slate-instant-replace/v/0.1.9](https://www.npmjs.com/package/slate-instant-replace/v/0.1.9)

Let me know if you find any issue 😉
