### ISSUE TITLE
Does not pass events to subsequent plugins

### ISSUE THREAD

**Issue by tommoor** [enzoferey/slate-instant-replace#5]
Hey Enzo, it looks like if you place this plugin before another one the events never make it through – I believe because you need to call `next()` method if no transforms are run – and you're only doing so in [one spot](https://github.com/enzoferey/slate-instant-replace/blob/master/lib/index.js#L23).

![image](https://user-images.githubusercontent.com/380914/68186358-cfcc7a00-ff58-11e9-991b-4a4b55aa3846.png)

Could be the case with this issue: https://github.com/enzoferey/slate-instant-replace/issues/3

**Comment by enzoferey** [comment]
Hi @tommoor ! Happy to see you over here 😄 

Regarding the issue, thank you very much for bringing it up. I'm currently not using the plugin in production so it's hard for me to be aware when changes happen (I'm pretty sure last time I upgraded the package `slate` was calling `next()` automatically at the end of the function).

I will check it in the next few hours and publish a fix if needed. Thanks again 👍 

Btw, I would love to see what you are working on that needs this plugin 😉

**Comment by enzoferey** [comment]
Published the fix in `v0.1.13` 👍

**Comment by enzoferey** [comment]
> Wraps hashtags in an inline node as you type.

Looks exactly like the kind of feature I created this library for 😁

If I remember well, your other option without this package is to write a very simple plugin that listens for “#” onKeyDown and toggles current inline to your choice. I remember looking at the source of some example of the website last time I implemented a mention plugin (same but with “@“ and showing a portal) but I can’t find anything related to it right now (not at my PC anyways). 

Anyways, it would probably be much more rigid than using this ~amazing~ library (and you can use it for other features) 😜
